Name = "eaerrors"
SID = "events-api"

[[error]]
    Name = "ErrResourceNotExists"
    StatusHTTP = 404
    Message = "Resource doesn't exist"
    Kind = 1

[[error]]
    Name = "ErrInternal"
    StatusHTTP = 500
    Message = "Internal error"
    Kind = 2

[[error]]
    Name = "ErrValidation"
    StatusHTTP = 400
    Message = "Validation error"
    Kind = 3

[[error]]
    Name = "ErrRequiredHeadersNotProvided"
    StatusHTTP = 400
    Message = "Required headers not provided"
    Kind = 4

[[error]]
    Name = "ErrInvalidRole"
    StatusHTTP = 403
    Message = "Invalid user role"
    Kind = 5

[[error]]
    Name = "ErrAccessError"
    StatusHTTP = 403
    Message = "Access denied"
    Kind = 6
