tags:
  db: true
  platformdb: false

replicaCount: 1

image:
  repository: containerum/events-api
  tag: v1.0.0
  pullPolicy: IfNotPresent
  secret:

service:
  port: 1667
  targetPort: 1667
  externalIP:

env:
  global:
    MONGO_LOGIN: "events_user"
    MONGO_DB: "events"
  local:
    MONGO_ADDR: "mongo-mongodb.mongo.svc.cluster.local:27017"
    MONGO_PASSWORD:

mongodb:
  persistence:
    enabled: false
  image:
    pullPolicy: IfNotPresent
  mongodbUsername: events_user
  mongodbDatabase: events
  # mongodbPassword: password
